nome = input('Qual o seu nome ? ')
idade = input('Qual a sua idade ? ')
dia = input('Dia: ')
mes = input('Mes: ')
ano = input('Ano: ')
peso = input('Qual o seu peso ? ')
print(nome,idade,peso)
print('Boas vindas ' + nome)
print('Voce nasceu no dia ',dia,'/',mes,'/',ano)
print('A soma desses numeros e ',int(dia) + int(mes) + int(ano))