valor4 = input('Digite algo: ')
print('é numero ou letra:  {}'.format(valor4.isalnum()))
print('é numero: {}'.format(valor4.isnumeric()))
print('é letra: {}'.format(valor4.isalpha()))
print('dentro do padrao ASCII: {}'.format(valor4.isascii()))
print('esta em minusculo: {}'.format(valor4.islower()))
print('esta em maiusculo: {}'.format(valor4.isupper()))
print('so tem espaco: {}'.format(valor4.isspace()))
print('1 letra maiusucula: {}'.format(valor4.istitle()))